#!/usr/bin/env python3
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "web" / "src" / "App.jsx"
OUT = ROOT / "web" / "public" / "audio"
MANIFEST = ROOT / "web" / "src" / "audioManifest.js"
TMP = ROOT / ".audio-tmp"
OUT.mkdir(parents=True, exist_ok=True)
TMP.mkdir(parents=True, exist_ok=True)
text = APP.read_text()
lesson_block = text.split("// ---------- 工具 ----------", 1)[0]
items = []
items += re.findall(r'\{\s*w:\s*"([^"]+)"', lesson_block)
items += re.findall(r'\{\s*en:\s*"([^"]+)"', lesson_block)
items = sorted(dict.fromkeys(items), key=str.lower)
manifest = {}
for item in items:
    digest = hashlib.sha1(item.encode("utf-8")).hexdigest()[:16]
    mp3 = OUT / f"{digest}.mp3"
    aiff = TMP / f"{digest}.aiff"
    manifest[item] = f"/audio/{digest}.mp3"
    if mp3.exists() and mp3.stat().st_size > 1000:
        continue
    subprocess.run(["say", "-v", "Samantha", "-r", "145", "-o", str(aiff), item], check=True)
    subprocess.run([
        "ffmpeg", "-y", "-loglevel", "error", "-i", str(aiff),
        "-codec:a", "libmp3lame", "-b:a", "96k", str(mp3)
    ], check=True)
    aiff.unlink(missing_ok=True)
MANIFEST.write_text(
    "// Generated by scripts/generate_audio_assets.py\n"
    "export const AUDIO_MANIFEST = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8"
)
print(json.dumps({"count": len(items), "manifest": str(MANIFEST), "audio_dir": str(OUT)}, ensure_ascii=False))
